// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKiExWR8TkW4ND5X8aVjTjsC23kTVbmFs',
    appId: '1:840490555730:web:17e0e13f08eb761b6e828b',
    messagingSenderId: '840490555730',
    projectId: 'nutriapp-28840',
    authDomain: 'nutriapp-28840.firebaseapp.com',
    storageBucket: 'nutriapp-28840.appspot.com',
    measurementId: 'G-6L4W3FZ6XY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdIIbTCYGJTMDMuloxsrTdP6_0R4yLWE',
    appId: '1:840490555730:android:a943e62b3c9b29056e828b',
    messagingSenderId: '840490555730',
    projectId: 'nutriapp-28840',
    storageBucket: 'nutriapp-28840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVScpH5arZYf7scjMlSzb6Bvyqw7Cn0x0',
    appId: '1:840490555730:ios:282d9ca24ec6e6c76e828b',
    messagingSenderId: '840490555730',
    projectId: 'nutriapp-28840',
    storageBucket: 'nutriapp-28840.appspot.com',
    iosBundleId: 'com.example.nutriapp',
  );
}
